In [5]:
#imports 

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [ ]:
# get the data

import os

if not os.path.exists('course_lead_scoring.csv'):
    !wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
else:
    print("File already exists — skipping download.")

File already exists — skipping download.

In [7]:
df = pd.read_csv('course_lead_scoring.csv')
df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

In [10]:
# data preparation - exploration

# transposes the dataframe to see more columns
df.head().T

,0,1,2,3,4
lead_source,paid_ads,social_media,events,paid_ads,referral
industry,NaN,retail,healthcare,retail,education
number_of_courses_viewed,1,1,5,2,3
annual_income,79450.0,46992.0,78796.0,83843.0,85012.0
employment_status,unemployed,employed,unemployed,NaN,self_employed
location,south_america,south_america,australia,australia,europe
interaction_count,4,1,3,1,3
lead_score,0.94,0.8,0.69,0.87,0.62
converted,1,0,1,0,1

In [17]:
df.columns = df.columns.str.lower().str.replace(' ', '_')   # cleans column names

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)  # lists categorical columns

for c in categorical_columns:  
    df[c] = df[c].str.lower().str.replace(' ', '_')   # cleans categorical values

df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

In [22]:
df.dtypes # checks data types of columns

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [23]:
df.isnull().sum()  # checks for missing values

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [26]:
df[categorical_columns] = df[categorical_columns].fillna('NA')  # fills missing values in categorical columns with 'NA'

df[categorical_columns].isnull().sum()  # checks again for missing values in categorical columns

lead_source          0
industry             0
employment_status    0
location             0
dtype: int64

In [ ]:
numerical_columns = df.select_dtypes(include=['number']).columns # gets list of numerical columns

df[numerical_columns] = df[numerical_columns].fillna(0.0)  # fills missing values in numerical columns with 0

df.isnull().sum()  # checks again for missing values in the dataframe

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [33]:
# Q1 - most freequent value in 'industry' column

df['industry'].mode()[0]    # returns the most frequent value in the 'industry' column

'retail'

In [ ]:
# Q2 - correlation matrix

df.corr(numeric_only=True)

,number_of_courses_viewed,annual_income,interaction_count,lead_score,converted
number_of_courses_viewed,1.000000,0.009770,-0.023565,-0.004879,0.435914
annual_income,0.009770,1.000000,0.027036,0.015610,0.053131
interaction_count,-0.023565,0.027036,1.000000,0.009888,0.374573
lead_score,-0.004879,0.015610,0.009888,1.000000,0.193673
converted,0.435914,0.053131,0.374573,0.193673,1.000000

In [44]:
# highest correlation is between annual_income and interaction_count (0.03))